package cap7;

import java.io.*;

/**
 * Created @2017/2/24 20:30
 */
public class PrintWriterTest {

    public static void main(String... args) throws IOException {

        // Init PW
        BufferedWriter bw = new BufferedWriter(new FileWriter("D:\\nick\\java_code\\log.txt"));

        PrintWriter pw = new PrintWriter(bw);
        PrintStream ps = System.err;

        pw.println("------------START auto generated by machine----------");


        // Init Reader
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        String s;

        while ((s = br.readLine()) != null) {
            if (s.equals("quit")) break;
            pw.println(s);
            pw.flush();

            // Extra
            ps.println(s);
        }


        // Clean and flush
        bw.close();
        pw.close();
        pw.flush();
        br.close();
    }

}
